# Generated by Django 4.0.6 on 2022-07-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
